package vista;

import controlador.Ctrl_Nota;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import modelo.Nota;

/**
 *
 * @author HP
 */
public class InterNota extends javax.swing.JInternalFrame {

    public InterNota() {
        initComponents();
        this.setSize(new Dimension(390, 350));
        this.setTitle("Nueva Nota");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_titulo = new javax.swing.JTextField();
        txt_contenido = new javax.swing.JTextField();
        txt_fechacreacion = new javax.swing.JTextField();
        txt_fechamodificacion = new javax.swing.JTextField();
        txt_prioridad = new javax.swing.JTextField();
        jButton_guardar = new javax.swing.JButton();
        jLab_titulo = new javax.swing.JLabel();
        jLab_contenido = new javax.swing.JLabel();
        jLab_fechac = new javax.swing.JLabel();
        jLab_fecham = new javax.swing.JLabel();
        jLab_prioridad = new javax.swing.JLabel();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nueva Nota");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Título:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 60, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Contenido:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 80, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("FechaCreacion:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 130, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("FechaModificacion:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 140, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Prioridad:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 90, -1));

        txt_titulo.setBackground(new java.awt.Color(0, 204, 204));
        txt_titulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_titulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_tituloKeyReleased(evt);
            }
        });
        getContentPane().add(txt_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 170, -1));

        txt_contenido.setBackground(new java.awt.Color(0, 204, 204));
        txt_contenido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_contenido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_contenidoKeyReleased(evt);
            }
        });
        getContentPane().add(txt_contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 170, -1));

        txt_fechacreacion.setBackground(new java.awt.Color(0, 204, 204));
        txt_fechacreacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_fechacreacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_fechacreacionKeyReleased(evt);
            }
        });
        getContentPane().add(txt_fechacreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 170, -1));

        txt_fechamodificacion.setBackground(new java.awt.Color(0, 204, 204));
        txt_fechamodificacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_fechamodificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_fechamodificacionKeyReleased(evt);
            }
        });
        getContentPane().add(txt_fechamodificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 170, -1));

        txt_prioridad.setBackground(new java.awt.Color(0, 204, 204));
        txt_prioridad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_prioridad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_prioridadKeyReleased(evt);
            }
        });
        getContentPane().add(txt_prioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 170, -1));

        jButton_guardar.setBackground(new java.awt.Color(255, 153, 153));
        jButton_guardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_guardar.setText("Guardar");
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 90, 30));

        jLab_titulo.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(jLab_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 75, 170, 15));

        jLab_contenido.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(jLab_contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 170, 20));

        jLab_fechac.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(jLab_fechac, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 155, 170, 13));

        jLab_fecham.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(jLab_fecham, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 195, 170, 13));

        jLab_prioridad.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(jLab_prioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 235, 170, 15));

        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed
        //validar campos
        if (txt_titulo.getText().isEmpty() && txt_contenido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "complete todo los campos");
            this.validar();
        } else {

            Nota nota = new Nota();
            Ctrl_Nota ctrl_Nota = new Ctrl_Nota();

            if (!ctrl_Nota.existeNota(txt_titulo.getText().trim())) {

                nota.setTitulo(txt_titulo.getText().trim());
                nota.setContenido(txt_contenido.getText().trim());
                nota.setFechaCreacion(txt_fechacreacion.getText().trim());
                nota.setFechaModificacion(txt_fechamodificacion.getText().trim());
                nota.setPrioridad(txt_prioridad.getText().trim());

                if (ctrl_Nota.guardar(nota)) {
                    JOptionPane.showMessageDialog(null, "Registro Guardado");
                    txt_titulo.setBackground(Color.green);
                    txt_contenido.setBackground(Color.green);
                    txt_fechacreacion.setBackground(Color.green);
                    txt_fechamodificacion.setBackground(Color.green);
                    txt_prioridad.setBackground(Color.green);
                } else {
                    JOptionPane.showMessageDialog(null, "Error al Guardar");
                }

            } else {
                JOptionPane.showMessageDialog(null, "El Cliente ya esta registrado en Base de Datos");
                txt_titulo.setBackground(Color.white);
                txt_contenido.setBackground(Color.white);
                txt_fechacreacion.setBackground(Color.white);
                txt_fechamodificacion.setBackground(Color.white);
                txt_prioridad.setBackground(Color.white);
            }
        }

        //metodo para limpiar
        this.Limpiar();

    }//GEN-LAST:event_jButton_guardarActionPerformed

    private void txt_tituloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tituloKeyReleased
        this.validar();
    }//GEN-LAST:event_txt_tituloKeyReleased

    private void txt_contenidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contenidoKeyReleased
        this.validar();
    }//GEN-LAST:event_txt_contenidoKeyReleased

    private void txt_fechacreacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fechacreacionKeyReleased
        this.validar();
    }//GEN-LAST:event_txt_fechacreacionKeyReleased

    private void txt_fechamodificacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fechamodificacionKeyReleased
        this.validar();
    }//GEN-LAST:event_txt_fechamodificacionKeyReleased

    private void txt_prioridadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_prioridadKeyReleased
        this.validar();
    }//GEN-LAST:event_txt_prioridadKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_guardar;
    private javax.swing.JLabel jLab_contenido;
    private javax.swing.JLabel jLab_fechac;
    private javax.swing.JLabel jLab_fecham;
    private javax.swing.JLabel jLab_prioridad;
    private javax.swing.JLabel jLab_titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JTextField txt_contenido;
    private javax.swing.JTextField txt_fechacreacion;
    private javax.swing.JTextField txt_fechamodificacion;
    private javax.swing.JTextField txt_prioridad;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables

    //metodo de limpiar
    private void Limpiar() {
        txt_titulo.setText("");
        txt_contenido.setText("");
        txt_fechacreacion.setText("");
        txt_fechamodificacion.setText("");
        txt_prioridad.setText("");
    }

    public void validar() {
        if (txt_titulo.getText().isEmpty()) {
            jLab_titulo.setText("*campo obligatorio ");
        } else {
            jLab_titulo.setText("");
        }
        if (txt_contenido.getText().isEmpty()) {
            jLab_contenido.setText("*campo obligatorio");

        } else {
            jLab_contenido.setText("");
        }
        if (txt_fechacreacion.getText().isEmpty()) {
            jLab_fechac.setText("*completar campo");

        } else {
            jLab_fechac.setText("");

        }
        if (txt_fechamodificacion.getText().isEmpty()) {
            jLab_fecham.setText("*completar campo");
        } else {
            jLab_fecham.setText("");
        }
        if (txt_prioridad.getText().isEmpty()) {
            jLab_prioridad.setText("*completar campo");

        } else {
            jLab_prioridad.setText("");
        }

    }

}
